### ISSUE TITLE
Warnings about "object should be created from async function"

### ISSUE THREAD

**Issue by chartjes** [tarekziade/molotov#120]
venv/lib/python3.7/site-packages/molotov/session.py:43
  /mnt/c/Users/chartjes/normandy/venv/lib/python3.7/site-packages/molotov/session.py:43: DeprecationWarning: Inheritance class LoggedClientSession from ClientSession is discouraged
    class LoggedClientSession(ClientSession):

contract-tests/test_api_v3.py::test_list
  /mnt/c/Users/chartjes/normandy/venv/lib/python3.7/site-packages/aiohttp/connector.py:730: DeprecationWarning: The object should be created from async function
    loop=loop)

contract-tests/test_api_v3.py::test_list
  /mnt/c/Users/chartjes/normandy/venv/lib/python3.7/site-packages/aiohttp/connector.py:735: DeprecationWarning: The object should be created from async function
    resolver = DefaultResolver(loop=self._loop)

contract-tests/test_api_v3.py::test_list
  /mnt/c/Users/chartjes/normandy/venv/lib/python3.7/site-packages/molotov/session.py:54: DeprecationWarning: The object should be created from async function
    connector=connector,  **kw)

contract-tests/test_api_v3.py::test_list
  /mnt/c/Users/chartjes/normandy/venv/lib/python3.7/site-packages/aiohttp/cookiejar.py:55: DeprecationWarning: The object should be created from async function
    super().__init__(loop=loop)

-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by chartjes** [comment]
Still seeing the same errors while using the latest version from the master branch

**Comment by n1ngu** [comment]
I think the code that caused those warnings was removed by virtue of https://github.com/loads/molotov/issues/125

**Comment by tarekziade** [comment]
fixed
