### ISSUE TITLE
multiprocessing-on-dill in pre-release

### ISSUE THREAD

**Issue by grazius** [tarekziade/molotov#139]
Hello
when i try to use bzt that use molotov i got this error with pipenv

```
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches multiprocessing_on_dill (from molotov==2.4->bzt==1.16.2->-r C:\Users\a24309\AppData\Local\Temp\1\pipenvozg8g50xrequirements\pipenv-ivcrzp5z-constraints.txt (line 4))
Skipped pre-versions: 3.5.0a4
```

pipenv make some checks on versions used and the usage of multiprocessing-on-dill in a pre-release is not a good pratice.
but as i see the package is only provided in a pre release version ...

i open also an issue on the multiprocessing-on-dill git repository
https://github.com/sixty-north/multiprocessing_on_dill/issues/6

Best regards

**Comment by n1ngu** [comment]
Seems similiar to https://github.com/ipython/ipython/issues/13454 so you can probably also workaround it by either explicitly requiring the alpha version for multiprocessing_on_dill
```
[packages]
multiprocessing_on_dill = "==3.5.0a4"
molotov = "*"
```
(but then you'll need to watch for future releases if you want any updates, but there's been 0 releases in 7 years so...)

Or you could either upgrade your pipenv, because recent pipenv versions will fallback to the available prerelease without errors for prereleased-only packages.

**Comment by n1ngu** [comment]
This is actually a pipenv issue but triggered by molotov's choice of rather immature hard dependencies.

So, on our side I think it would be most adequate to move multiprocessing_on_dill to an extra dependency so people can opt out of it at the expense of reduced molotov functionality. I think this should be addressed regardless of package resolvers capability of resolving prereleased-only dependencies.

**Comment by grazius** [comment]
pipenv allow the pull of pre release with the - - pre option but in general it's not a good idea to make a release that depend on a snap, pre release version.

**Comment by n1ngu** [comment]
Looking into it, it seems that the multiprocessing_on_dill usage is ubiquitous across the molotov codebase, so fat chance for the extra requirement idea.

It totally replaces the multiprocessing standard module, so molotov is effectively running a stale copy of multiprocessing 7 years in the past regardless of your python interpreter.

I think, at the very least, the multiprocess project should be considered to replace multiprocessing_on_dill: https://github.com/uqfoundation/multiprocess#major-changes

The alternative is reworking molotov internals to avoid the need to serialize unpickable objects with dill?

**Comment by tarekziade** [comment]
I moved to `multiprocess` -- This will require lots of testing before I release `2.6`
