### ISSUE TITLE
add the ability to configure a test suite

### ISSUE THREAD

**Issue by tarekziade** [tarekziade/molotov#40]
from the CLI a sorted list of tests we want to run instead of scenario weights

**Comment by tarekziade** [comment]
After some thoughts about this I should mention that we already have the ability to run one single scenario with --single-mode and have that scenario call sub-scenarios, like ap-loadtest. 

Now I think we could add a CLI option called "--suite"

--suite could provide the sequence of functions to run, e.g.

```sh
$ molotov mytest.py --suite one,two,three
```

In that setup, each worker follow the sequence in a loop.

**Comment by rpappalax** [comment]
i was wondering if we might also allow weights weights w/ specified scenarios by specifying them together with function names, perhaps in a dictionary like so: --suite "{one:10,two:5,three:30}"  or simply, as you mentioned, assuming all weights equivalent --suite "one,two,three"

**Comment by tarekziade** [comment]
The weights are used to randomly pick the scenario. 

If we pass {one:10,two:5,three:30} it means we assign the weights, and when a worker picks the next scenario it will have 10/45 chances to get one, 5/40 chance to get two etc..

In other words, you will still get a random sequence.

If we pass {one:10,two:10,three:10} it works the same, e.g. each function gets 1/3 chance to get picked.

If this is the goal, it sounds great and I can add that. On my side I thought the goal was to have a specific sequence with no randomness at all, thus my proposal. of just passing the sequence.

**Comment by tarekziade** [comment]
I think a test suite can be done through a test that triggers tests itself. I think it allows more flexibility than to add something at the configuration level
